---
- name: Shutdown cluster servers
  hosts: server
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Shutdown
      community.general.shutdown:

- name: Shutdown cluster agents staggered
  hosts: agent
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
