---

- name: Run the equivalent of "apt update" as a separate step.
  ansible.builtin.apt:
    update_cache: yes

- name: Run the equivalent of "apt ugrade" as a separate step.
  ansible.builtin.apt:
    name: "*"
    state: latest
